version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLER_VERSION: 2.2.11
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7

    working_directory: ~/local-elections

    steps:
      - checkout
      - run: gem install bundler:2.2.11
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # yarn install
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack
      
      # run tests!
      - run:
          name: execute tests
          command: bundle exec rspec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      
      - run:
          name: install packages
          command: npm install
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run :
          name: run test
          command: npm test

      - run:
          name: post coverage
          command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
     
      - run:
          name: run list
          command: npm run list

      # run rubocop
      - run:
          name: run rubocop
          command: bundle exec rubocop
